Credit Card Fraud Detection Problem

Import Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tp
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras import optimizers
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
print (tf.__version__)

2.4.1


# Load Data

In [2]:
data=pd.read_csv("/content/creditcard.csv")

# Data Analysis

In [3]:
data.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [4]:
data.shape

(284807, 31)

There are 31 Columns and 284,807 rows of transactions

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

# Data Cleaning

Missing Values

In [6]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
np.where(data.applymap(lambda x: x=='') )

(array([], dtype=int64), array([], dtype=int64))

In [8]:
data.describe()

Time            V1  ...         Amount          Class
count  284807.000000  2.848070e+05  ...  284807.000000  284807.000000
mean    94813.859575  3.919560e-15  ...      88.349619       0.001727
std     47488.145955  1.958696e+00  ...     250.120109       0.041527
min         0.000000 -5.640751e+01  ...       0.000000       0.000000
25%     54201.500000 -9.203734e-01  ...       5.600000       0.000000
50%     84692.000000  1.810880e-02  ...      22.000000       0.000000
75%    139320.500000  1.315642e+00  ...      77.165000       0.000000
max    172792.000000  2.454930e+00  ...   25691.160000       1.000000

[8 rows x 31 columns]

In [9]:
not_fraud = data[data['Class']==0] 
fraud = data[data['Class'] == 1]

In [10]:
not_fraud = not_fraud.sample(fraud.shape[0])
not_fraud.shape
data= fraud.append(not_fraud, ignore_index=True)
data.shape
data['Class'].value_counts()
x_data = data.drop(columns = 'Class', axis=0)
label = data['Class']

In [11]:
not_fraud.shape

(492, 31)

In [12]:
fraud.shape

(492, 31)

Split the data

In [13]:
training_data, testing_data, training_labels, testing_labels = train_test_split(x_data, label, test_size = .3, random_state=1, stratify= label)

In [14]:
amt_zero = np.where(data.Amount.apply(lambda x: x == 0))
(data['Amount'].values == 0 ).sum()

32

Standarize the data

In [15]:
mean = training_data.mean(axis=0) 
training_data -= mean
std = training_data.std(axis=0) 
training_data /=std
testing_data -=mean 
testing_data /=std

In [16]:
testing_data.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
dtype: object

Model - relu

In [17]:
model_relu = Sequential()
model_relu.add(Dense(10, activation= 'relu',input_shape =(training_data.shape[1],)))
model_relu.add(Dropout(0.3))
model_relu.add(Dense(8, activation= 'relu')) 
model_relu.add(Dropout(0.3))
model_relu.add(Dense(6, activation= 'relu')) 
model_relu.add(Dropout(0.3))
model_relu.add(Dense(1, activation= 'sigmoid'))

Model - Tanh

In [18]:
model_tanh = Sequential()
model_tanh.add(Dense(10, activation= 'tanh',input_shape=(training_data.shape[1],))) 
model_tanh.add(Dropout(0.3)) 
model_tanh.add(Dense(8, activation= 'tanh')) 
model_tanh.add(Dropout(0.3)) 
model_tanh.add(Dense(6, activation= 'tanh')) 
model_tanh.add(Dropout(0.3)) 
model_tanh.add(Dense(1, activation= 'sigmoid'))

Compilation Step

In [19]:
model_relu.compile(loss ='binary_crossentropy', optimizer='RMSprop', metrics=['accuracy'])

In [20]:
history_relu = model_relu.fit(training_data, training_labels, epochs=100, validation_split= 0.3)

Epoch 1/100
16/16 [==============================] - 1s 38ms/step - loss: 0.6376 - accuracy: 0.5792 - val_loss: 0.5747 - val_accuracy: 0.6715
Epoch 2/100
16/16 [==============================] - 0s 4ms/step - loss: 0.6178 - accuracy: 0.6158 - val_loss: 0.5586 - val_accuracy: 0.7681
Epoch 3/100
16/16 [==============================] - 0s 4ms/step - loss: 0.5773 - accuracy: 0.7089 - val_loss: 0.5455 - val_accuracy: 0.8116
Epoch 4/100
16/16 [==============================] - 0s 4ms/step - loss: 0.5596 - accuracy: 0.7299 - val_loss: 0.5351 - val_accuracy: 0.8116
Epoch 5/100
16/16 [==============================] - 0s 5ms/step - loss: 0.6059 - accuracy: 0.7314 - val_loss: 0.5242 - val_accuracy: 0.8261
Epoch 6/100
16/16 [==============================] - 0s 5ms/step - loss: 0.5339 - accuracy: 0.8041 - val_loss: 0.5157 - val_accuracy: 0.8599
Epoch 7/100
16/16 [==============================] - 0s 5ms/step - loss: 0.5318 - accuracy: 0.7589 - val_loss: 0.5059 - val_accuracy: 0.8647
Epoch 8/100


In [21]:
model_tanh.compile(loss ='binary_crossentropy', optimizer='RMSprop', metrics=['accuracy'])

In [22]:
history_tanh = model_tanh.fit(training_data, training_labels, epochs=100, validation_split= 0.3)

Epoch 1/100
16/16 [==============================] - 1s 19ms/step - loss: 0.8071 - accuracy: 0.4872 - val_loss: 0.6450 - val_accuracy: 0.6377
Epoch 2/100
16/16 [==============================] - 0s 4ms/step - loss: 0.7007 - accuracy: 0.5887 - val_loss: 0.5580 - val_accuracy: 0.7681
Epoch 3/100
16/16 [==============================] - 0s 4ms/step - loss: 0.6326 - accuracy: 0.6574 - val_loss: 0.4918 - val_accuracy: 0.8357
Epoch 4/100
16/16 [==============================] - 0s 4ms/step - loss: 0.5564 - accuracy: 0.7014 - val_loss: 0.4416 - val_accuracy: 0.8502
Epoch 5/100
16/16 [==============================] - 0s 4ms/step - loss: 0.5295 - accuracy: 0.7409 - val_loss: 0.4009 - val_accuracy: 0.8744
Epoch 6/100
16/16 [==============================] - 0s 4ms/step - loss: 0.5045 - accuracy: 0.7590 - val_loss: 0.3694 - val_accuracy: 0.8841
Epoch 7/100
16/16 [==============================] - 0s 4ms/step - loss: 0.4792 - accuracy: 0.7803 - val_loss: 0.3449 - val_accuracy: 0.8889
Epoch 8/100


Evaluation / Prediction

In [23]:
test_loss_Score_relu, test_acc_score_relu = model_relu.evaluate(testing_data, testing_labels)

10/10 [==============================] - 0s 2ms/step - loss: 0.2209 - accuracy: 0.9223


In [24]:
test_loss_Score_tanh, test_acc_score_tanh = model_tanh.evaluate(testing_data, testing_labels)

10/10 [==============================] - 0s 2ms/step - loss: 0.2395 - accuracy: 0.9257


In [25]:
test_acc_score_relu*100

92.22972989082336

In [26]:
model_relu.predict(np.array(testing_data.iloc[1,:]).reshape(1,testing_data.shape[1]))

array([[0.16147432]], dtype=float32)

In [27]:
pred_score = model_relu.predict(testing_data).astype(dtype='u8')

In [28]:
pred_label = (pred_score > 0.5)
tf.math.confusion_matrix(
    testing_labels, pred_label, num_classes=2, weights=None, dtype=tf.dtypes.int32,name=None)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[148,   0],
       [ 57,  91]], dtype=int32)>

In [29]:
np.count_nonzero(pred_label)

91

In [30]:
test_acc_score_tanh*100

92.56756901741028

In [31]:
model_tanh.predict(np.array(testing_data.iloc[1,:]).reshape(1,testing_data.shape[1]))

array([[0.01965263]], dtype=float32)

In [32]:
pred_score = model_tanh.predict(testing_data).astype(dtype='u8')

In [33]:
pred_label = (pred_score > 0.5)
tf.math.confusion_matrix(
    testing_labels, pred_label, num_classes=2, weights=None, dtype=tf.dtypes.int32,name=None)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[148,   0],
       [148,   0]], dtype=int32)>

In [34]:
np.count_nonzero(pred_label)

0